In [1]:
import torch
import math
import torch.nn as nn

In [5]:
seq_len = 5; d_model = 20
pe = torch.zeros(seq_len, d_model)
position = torch.arange(0, seq_len, dtype=torch.float).unsqueeze(1)
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(1000.0) / d_model))
print(position.shape)
print(div_term.shape)
print((position * div_term).shape)
#Apply the sin to even positions
print("pe1:", pe[:, 0::2].shape)
print("pe2", pe[:, 1::2].shape)
print("div: ",(position * div_term).shape)
pe[:, 0::2] = torch.sin(position * div_term)
pe[:, 1::2] = torch.cos(position * div_term)
pe = pe.unsqueeze(0)
print("pe: ", pe.shape)

torch.Size([5, 1])
torch.Size([10])
torch.Size([5, 10])
pe1: torch.Size([5, 10])
pe2 torch.Size([5, 10])
div:  torch.Size([5, 10])
pe:  torch.Size([1, 5, 20])


In [10]:
x = torch.rand(2,4,10) #batch_size x seq_len x dim
mean1 = x.mean(dim=-1)
print(mean1.shape)
print(mean1)
mean2 = x.mean(dim=-1, keepdim=True)
print(mean2.shape)
print(mean2)
x = x - mean2
print(x.shape)



torch.Size([2, 4])
tensor([[0.5921, 0.4936, 0.2702, 0.4509],
        [0.5168, 0.4853, 0.4650, 0.5910]])
torch.Size([2, 4, 1])
tensor([[[0.5921],
         [0.4936],
         [0.2702],
         [0.4509]],

        [[0.5168],
         [0.4853],
         [0.4650],
         [0.5910]]])
torch.Size([2, 4, 10])


In [15]:
torch.ones(2).requires_grad_(True)

tensor([1., 1.], requires_grad=True)

In [16]:
nn.Parameter(torch.ones(2))

Parameter containing:
tensor([1., 1.], requires_grad=True)

In [3]:
x = torch.rand(2,3,4,5) #(B, h, S, d)
x.transpose(1,2).contiguous().shape

torch.Size([2, 4, 3, 5])

In [3]:
x = torch.rand(2,3,4)
mean = torch.rand(2,3,1) #(B, S, d)
y = torch.ones(4)
print((x - mean).shape)
print(((x-mean)*y).shape)

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
